files:
  - source: /apps/web/src/i18n/messages/en.po
    translation: /apps/web/src/i18n/messages/%two_letters_code%.%file_extension%
  - source: /packages/email/src/messages/en.json
    translation: /packages/email/src/messages/%two_letters_code%.%file_extension%
