blank_issues_enabled: false
contact_links:
  - name: View API documentation
    url: https://virtbase.com/api/docs
    about: Check out the official API documentation
  - name: Get community support on GitHub Discussions
    url: https://github.com/virtbase/virtbase/discussions
    about: Start a discussion to share ideas and ask questions