/*
 *   Copyright (c) 2026 Janic Bellmann
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { gzipSync } from "node:zlib";

/**
 * Bakes the export document's fonts into a TypeScript module.
 *
 * The document is rendered from three different places - a workflow step, an
 * admin server action, and the test suite - and each one bundles this package
 * differently. Reading the `.ttf` off disk failed in two distinct ways: the
 * bundler rewrites `import.meta.url` to a chunk path where the file is not,
 * and it hands the action a `URL` from a different realm than `node:fs`
 * checks against. A module has none of those problems.
 *
 * Gzipped first: a TrueType file is about 45% of its size compressed, and the
 * bytes sit in the server bundle either way.
 *
 *   bun -F @virtbase/api embed-fonts
 */
const DIR = join(import.meta.dir, "../src/privacy/export");

const encode = (name: string) =>
  gzipSync(readFileSync(join(DIR, "fonts", name)), { level: 9 }).toString(
    "base64",
  );

const header = readFileSync(join(import.meta.dir, "embed-fonts.ts"), "utf8")
  .split("*/")[0]
  .concat("*/");

writeFileSync(
  join(DIR, "fonts.generated.ts"),
  `${header}

// Generated by \`bun -F @virtbase/api embed-fonts\`. Do not edit by hand;
// change the .ttf under ./fonts and re-run it.

export const ARIAL_GZIP_BASE64 =
  "${encode("arial.ttf")}";

export const ARIAL_BLACK_GZIP_BASE64 =
  "${encode("arial-black.ttf")}";
`,
);

console.log("wrote src/privacy/export/fonts.generated.ts");
