/*
 *   Copyright (c) 2026 Janic Bellmann
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { sql } from "drizzle-orm";
import * as d from "drizzle-orm/pg-core";
import { createId } from "../utils/create-id";
import { datacenters } from "./datacenters";
import { proxmoxNodeGroups } from "./proxmox-node-groups";

/**
 * A Proxmox VE node represents a physical machine within a datacenter
 * that can host multiple servers.
 */
export const proxmoxNodes = d.snakeCase.table(
  "proxmox_nodes",
  {
    id: d
      .text()
      .primaryKey()
      .$default(() => createId({ prefix: "pn_" })),
    /**
     * The ID of the datacenter where the Proxmox VE node is located.
     */
    datacenterId: d
      .text()
      .notNull()
      .references(() => datacenters.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    /**
     * The ID of the Proxmox VE node group this Proxmox VE node belongs to.
     */
    proxmoxNodeGroupId: d
      .text()
      .notNull()
      .references(() => proxmoxNodeGroups.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    /**
     * The hostname of the Proxmox VE node as configured
     * in the Proxmox cluster.
     *
     * @example "epyc01"
     */
    hostname: d.text().notNull(),
    /**
     * The FQDN of the Proxmox VE node where the API is accessible.
     *
     * @example "epyc01.example.com"
     */
    fqdn: d.text().notNull(),
    /**
     * The API token ID used to authenticate with the Proxmox VE node.
     * In the format <user_name>@<realm>!<token_name>.
     *
     * @example "api@pam!virtbase"
     */
    tokenID: d.text().notNull(),
    /**
     * The API token secret used to authenticate with the Proxmox VE node.
     * This is a UUID generated by the Proxmox VE node.
     *
     * @example "f7d62f02-eb10-413e-b8f1-6dd8a9902885"
     */
    tokenSecret: d.text().notNull(),
    /**
     * The description of the storage of the Proxmox VE node.
     *
     * @example "Samsung PM9A1 1TB NVMe SSD"
     */
    storageDescription: d.text(),
    /**
     * The description of the memory of the Proxmox VE node.
     *
     * @example "Samsung 16GB DDR4-2666MHz"
     */
    memoryDescription: d.text(),
    /**
     * The description of the CPU of the Proxmox VE node.
     *
     * @example "AMD EPYC 7443P"
     */
    cpuDescription: d.text(),
    /**
     * The maximum possible network bandwidth of the Proxmox VE node in MB/s.
     *
     * @default 125 MB/s = 1 Gbit/s
     */
    netrate: d.integer().default(125),
    /**
     * If set, the maximum number of guests that should be running on the Proxmox VE node.
     *
     * @default null
     */
    guestLimit: d.integer(),
    /**
     * If set, the maximum memory that should be used on the Proxmox VE node in MiB.
     *
     * @default null
     */
    memoryLimit: d.integer(),
    /**
     * If set, the maximum storage that should be used on the Proxmox VE node in GiB.
     * This is not relevant if a shared storage is used.
     *
     * @default null
     */
    storageLimit: d.integer(),
    /**
     * If set, the maximum network bandwidth that should be used on the Proxmox VE node in MB/s.
     *
     * @default null
     */
    netrateLimit: d.smallint(),
    /**
     * If set, the maximum number of vCores that should be used on the Proxmox VE node.
     *
     * @default null
     */
    coresLimit: d.smallint(),
    /**
     * The name of the storage used for custom cloud-init snippets.
     *
     * @example "local-lvm", "cephfs", "nfs"
     */
    snippetStorage: d.text().notNull(),
    /**
     * The name of the storage used for backups.
     *
     * @example "local-lvm", "cephfs", "nfs"
     */
    backupStorage: d.text().notNull(),
    /**
     * The name of the storage used for ISO image downloads.
     *
     * @example "local-lvm", "cephfs", "nfs"
     */
    isoDownloadStorage: d.text().notNull(),
    createdAt: d
      .timestamp({ withTimezone: true, mode: "date" })
      .defaultNow()
      .notNull(),
    updatedAt: d
      .timestamp({ withTimezone: true, mode: "date" })
      .defaultNow()
      .notNull()
      .$onUpdate(() => sql`now()`),
  },
  (t) => [d.index().on(t.datacenterId), d.index().on(t.proxmoxNodeGroupId)],
);

export type DatabaseProxmoxNode = typeof proxmoxNodes.$inferSelect;
