/*
 *   Copyright (c) 2026 Janic Bellmann
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { relations, sql } from "drizzle-orm";
import { index, pgTable } from "drizzle-orm/pg-core";
import { createId } from "../utils/create-id";
import { datacenters } from "./datacenters";
import { proxmoxNodeGroups } from "./proxmox-node-groups";
import { proxmoxTemplatesToProxmoxNodes } from "./proxmox-templates-to-proxmox-nodes";
import { servers } from "./servers";

/**
 * A Proxmox VE node represents a physical machine within a datacenter
 * that can host multiple servers.
 */
export const proxmoxNodes = pgTable(
  "proxmox_nodes",
  (t) => ({
    id: t
      .text()
      .primaryKey()
      .$default(() => createId({ prefix: "pn_" })),
    /**
     * The ID of the datacenter where the Proxmox VE node is located.
     */
    datacenterId: t
      .text()
      .notNull()
      .references(() => datacenters.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    /**
     * The ID of the Proxmox VE node group this Proxmox VE node belongs to.
     */
    proxmoxNodeGroupId: t
      .text()
      .notNull()
      .references(() => proxmoxNodeGroups.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
    /**
     * The hostname of the Proxmox VE node as configured
     * in the Proxmox cluster.
     *
     * @example "epyc01"
     */
    hostname: t.text().notNull(),
    /**
     * The FQDN of the Proxmox VE node where the API is accessible.
     *
     * @example "epyc01.example.com"
     */
    fqdn: t.text().notNull(),
    /**
     * The API token ID used to authenticate with the Proxmox VE node.
     * In the format <user_name>@<realm>!<token_name>.
     *
     * @example "api@pam!virtbase"
     */
    tokenID: t.text().notNull(),
    /**
     * The API token secret used to authenticate with the Proxmox VE node.
     * This is a UUID generated by the Proxmox VE node.
     *
     * @example "f7d62f02-eb10-413e-b8f1-6dd8a9902885"
     */
    tokenSecret: t.text().notNull(),
    /**
     * The description of the storage of the Proxmox VE node.
     *
     * @example "Samsung PM9A1 1TB NVMe SSD"
     */
    storageDescription: t.text(),
    /**
     * The description of the memory of the Proxmox VE node.
     *
     * @example "Samsung 16GB DDR4-2666MHz"
     */
    memoryDescription: t.text(),
    /**
     * The description of the CPU of the Proxmox VE node.
     *
     * @example "AMD EPYC 7443P"
     */
    cpuDescription: t.text(),
    /**
     * The maximum possible network bandwidth of the Proxmox VE node in MB/s.
     *
     * @default 125 MB/s = 1 Gbit/s
     */
    netrate: t.integer().default(125),
    /**
     * If set, the maximum number of guests that should be running on the Proxmox VE node.
     *
     * @default null
     */
    guestLimit: t.integer(),
    /**
     * If set, the maximum memory that should be used on the Proxmox VE node in MiB.
     *
     * @default null
     */
    memoryLimit: t.integer(),
    /**
     * If set, the maximum storage that should be used on the Proxmox VE node in GiB.
     * This is not relevant if a shared storage is used.
     *
     * @default null
     */
    storageLimit: t.integer(),
    /**
     * If set, the maximum network bandwidth that should be used on the Proxmox VE node in MB/s.
     *
     * @default null
     */
    netrateLimit: t.smallint(),
    /**
     * If set, the maximum number of vCores that should be used on the Proxmox VE node.
     *
     * @default null
     */
    coresLimit: t.smallint(),
    /**
     * The name of the storage used for custom cloud-init snippets.
     *
     * @example "local-lvm", "cephfs", "nfs"
     */
    snippetStorage: t.text().notNull(),
    /**
     * The name of the storage used for backups.
     *
     * @example "local-lvm", "cephfs", "nfs"
     */
    backupStorage: t.text().notNull(),
    createdAt: t
      .timestamp({ withTimezone: true, mode: "date" })
      .defaultNow()
      .notNull(),
    updatedAt: t
      .timestamp({ withTimezone: true, mode: "date" })
      .defaultNow()
      .notNull()
      .$onUpdate(() => sql`now()`),
  }),
  (t) => [index().on(t.datacenterId), index().on(t.proxmoxNodeGroupId)],
);

export const proxmoxNodesRelations = relations(
  proxmoxNodes,
  ({ one, many }) => ({
    datacenter: one(datacenters, {
      fields: [proxmoxNodes.datacenterId],
      references: [datacenters.id],
    }),
    proxmoxNodeGroup: one(proxmoxNodeGroups, {
      fields: [proxmoxNodes.proxmoxNodeGroupId],
      references: [proxmoxNodeGroups.id],
    }),
    proxmoxTemplates: many(proxmoxTemplatesToProxmoxNodes),
    servers: many(servers),
  }),
);
